### ISSUE TITLE
Problem z autotworzeniem nowej bazy w MongoDB

### ISSUE THREAD

**Issue by debian-sh** [groovy354/Sealious#100]
Repo zcheckoutowane po issue#99, sealious startuje, wczytuje config, lecz nie tworzy nowej bazy danych.

`		"datastore.mongo":{
			"embedded": false,
			"db_name": "placetag_db"
		}
`

Wynik z Robomongo dla localhostu:

![selection_009](https://cloud.githubusercontent.com/assets/5663277/6565253/0273d5f8-c6af-11e4-9908-d7c68bf7397a.png)

**Comment by theadimar21** [comment]
Wydaje mi się, że mongo tworzy nową bazę samoistnie podczas wykonywania
insert, więc spróbuj coś do niej wsadzić.
​

**Comment by simplypixi** [comment]
A mi się wydaję (:P), że domyślnie Sealious nie tworzy bazy. Trzeba ją
utworzyć. Automatycznie tworzą się tylko kolekcje. ;)

Mariusz Wójcik
tel. 507-386-287

Napisz wiadomość >> <pixiproject@gmail.com>
Przejdź do portfolio >> <http://simplypixi.portfoliobox.me/projects>
[image: 2]
<http://oferia.pl/wykonawca/pixel93/323171?utm_source=powiad&utm_medium=email&utm_campaign=sygnatura_mail>

W dniu 10 marca 2015 08:18 użytkownik theadimar21 <notifications@github.com>
napisał:

**Comment by debian-sh** [comment]
Ok wysłałem POST na bazę po zalogowaniu dane się dodały, są dostępne na zapytanie GET, ale pod jakim portem mamy do nich dostęp? Pod robomongo mogę zobaczyć bazę na localhoście pod portem 27017, ale nie ma tam bazy z kolekcjami, pod portem 7766 nie da się połączyć.

**Comment by groovy354** [comment]
Uruchamiasz Sealiousa w trybie lokalnym. Layer_config, gdzie widnieje port
7766, tyczy się tylko trybu rozproszonego

**Comment by debian-sh** [comment]
Wszystko ok, w terminalu dane są widoczne. Problem leżał po stronie Robomongo
