### ISSUE TITLE
[error-handling] Klasa/moduł prometeuszowy, który ujednolici rzucanie błędu

### ISSUE THREAD

**Issue by groovy354** [groovy354/Sealious#42]
Należy stworzyć klasę Error, która będzie miała atrybuty "err_message", "err_code" i "err_module", która ujednolici sposób formatowania i rzucania błędów.

**Comment by theadimar21** [comment]
```The works continue.```

```dispatcher-wrapper.js```, linijki: 48 i 56.
Nie zmieniam na razie typu błędu, na ```SealiousErrors```, najpierw trzeba przemyśleć samo rzucanie błędu.

**Comment by groovy354** [comment]
Myślę, że możemy zamknąć. Teraz tylko pozostaje pamiętać, aby zawsze korzystać z Sealiousowych błędów :)
